{% set name = "dpcmaps" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 622ce8d820d3c1550704bdf39b2c002bfb1f2c941d74173813b5f6aa552f698f

build:
  number: 1
  noarch: python
  entry_points:
    - dpcmaps = dpcmaps.dpc_gui:run_dpc_gui
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - matplotlib-base
    - numpy
    - pillow
    - psutil
    - pyqt
    - scikit-image
    - tifffile

test:
  imports:
    - dpcmaps
    - dpcmaps.db_config
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NSLS-II/dpcmaps
  summary: Software for Diffraction Phase Correlation (DPC) analysis
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: http://nsls-ii.github.io/dpcmaps
  dev_url: https://github.com/NSLS-II/dpcmaps

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
